global_options = {}

K_HELP = 'help'

K_START_ACTION = 'go'
K_DEFAULT_START_ACTION = ''

K_BINS = 'bins'
K_BINS_DEFAULT_VALUE = 16

K_CLIFFS = 'cliffs'
K_CLIFFS_DEFAULT_VALUE = .147

K_FAR = 'far'
K_FAR_DEFAULT_VALUE = .95

K_HALVES = 'halves'
K_HALVES_DEFAULT_VALUE = 512

K_MIN = 'min'
K_MIN_DEFAULT_VALUE = .5

K_MAX = 'max'
K_MAX_DEFAULT_VALUE = 512

K_DISTANCE_COEF = 'p'
K_DEFAULT_DISTANCE_COEF = 2

K_REST = 'rest'
K_REST_DEFAULT_VALUE = 4

K_REUSE = 'reuse'
K_REUSE_DEFAULT_VALUE = True

K_SEED = 'seed'
K_DEFAULT_SEED_VALUE = 937162211

K_FILE = 'file'
K_DEFAULT_DATA_FILE="../../../etc/data/auto93.csv"

HUGE_VALUE = 1000000000000000

