global_options = {}

K_SEED = 'seed'
K_DEFAULT_SEED_VALUE = 937162211
K_HELP = 'help'
K_START_ACTION = 'go'
K_FILE="file"
K_DEFAULT_DATA_FILE="../../../etc/data/auto93.csv"
K_DEFAULT_START_ACTION = 'data_read'
K_FARAWAY = 'faraway'
K_DEFAULT_FARAWAY_VALUE = 0.95
K_MIN = 'min'
K_DEFAULT_MIN_VALUE = .5
K_DISTANCE_COEF = 'p'
K_DEFAULT_DISTANCE_COEF = 2
K_SAMPLE = 'sample'
K_DEFAULT_SAMPLE_VALUE = 512

